# fly.toml app configuration file generated for neighborhood-app on 2025-03-07T22:01:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'neighborhood-app'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  auto_stop_timeout = 3600 # 1 hour timeout

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512